# Generated by Django 5.2.3 on 2025-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
