# Generated by Django 5.2.3 on 2025-07-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_contactinfo_faq_knowledgebaseentry_linkedaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payments', to='clients.client')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
