# Generated by Django 5.2.3 on 2025-07-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_balance_client_business_type_client_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
    ]
