# Generated by Django 5.2.3 on 2025-07-18 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finances',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
