# Generated by Django 5.2.3 on 2025-07-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_image',
        ),
    ]
