# Generated by Django 5.2.3 on 2025-08-08 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenttransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Processing', 'Processing')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
