# Generated by Django 5.2.3 on 2025-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_recenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], default='Cash In', max_length=20),
        ),
    ]
