# Generated by Django 5.2.3 on 2025-08-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_recenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttransaction',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
