# Generated by Django 5.2.3 on 2025-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffcommissionhistory_remove_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawhistory',
            name='date_withdrawn',
        ),
        migrations.AddField(
            model_name='withdrawhistory',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Airtel', 'Airtel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='staff.staff'),
        ),
    ]
