# Generated by Django 5.2.3 on 2025-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_withdrawhistory_date_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawhistory',
            name='requested_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
