# Generated by Django 5.2.3 on 2025-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_withdrawhistory_requested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
