# Generated by Django 5.2.3 on 2025-07-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_finances_balance'),
        ('staff', '0008_alter_withdrawhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recent_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transaction', to='clients.recenttransaction'),
        ),
        migrations.DeleteModel(
            name='Earnings',
        ),
    ]
