# Generated by Django 5.2.3 on 2025-07-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_transaction_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
    ]
