# Generated by Django 5.2.3 on 2025-07-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_finances_balance'),
        ('staff', '0012_remove_transaction_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientassignment',
            unique_together={('staff', 'client')},
        ),
    ]
