# Generated by Django 5.2.3 on 2025-08-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_clientassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
