# Generated by Django 5.2.3 on 2025-08-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='completed', max_length=50),
            preserve_default=False,
        ),
    ]
