# Generated by Django 5.2.3 on 2025-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='processing', max_length=50),
        ),
    ]
