# Generated by Django 5.2.3 on 2025-07-08 20:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('api_secret', models.CharField(max_length=255)),
                ('allowed_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10), default=list, help_text='Modes the merchant can operate in', size=None)),
                ('default_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('max_amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Collection'), (2, 'Disbursement')])),
                ('out_trade_no', models.CharField(db_index=True, max_length=36)),
                ('amount', models.BigIntegerField(help_text='Amount in smallest currency unit (e.g. shillings, cents)')),
                ('channel', models.IntegerField()),
                ('trader_id', models.CharField(max_length=20)),
                ('trader_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('notify_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='config.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error')], default='sent', max_length=10)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('original_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_requests', to='config.request')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField()),
                ('standardized_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregator_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='config.aggregatorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_credentials', to='config.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'mode')},
            },
        ),
    ]
