# Generated by Django 5.2.3 on 2025-07-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('balance', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQueryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('out_trade_no', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('pay_status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Success'), (2, 'Failed')])),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('out_trade_no', models.CharField(max_length=36)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_payment_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_collect_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payer_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payee_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('pay_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Success'), (2, 'Failed')])),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('out_trade_no', models.CharField(max_length=36)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_payment_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_collect_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payer_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payee_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('pay_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidBillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('channel', models.IntegerField(choices=[(1, 'MTN'), (2, 'Airtel')])),
                ('transaction_type', models.IntegerField(choices=[(1, 'Collection'), (2, 'Disbursement')])),
                ('trader_id', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidBillResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('trader_id', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StatementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('start_time', models.CharField(blank=True, max_length=8, null=True)),
                ('end_time', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('statement_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('channel', models.IntegerField(choices=[(1, 'MTN'), (2, 'Airtel')])),
                ('out_trade_no', models.CharField(max_length=36)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.IntegerField(choices=[(1, 'Collection'), (2, 'Disbursement')])),
                ('trader_id', models.CharField(max_length=20)),
                ('trader_full_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedOrderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('out_trade_no', models.CharField(max_length=36)),
                ('transaction_id', models.CharField(max_length=100)),
                ('actual_payment_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_collect_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payer_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payee_charge', models.DecimalField(decimal_places=6, max_digits=12)),
                ('channel_charge', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='aggregatorrequest',
            name='original_request',
        ),
        migrations.RemoveField(
            model_name='response',
            name='aggregator_request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='AggregatorCredentials',
        ),
        migrations.DeleteModel(
            name='AggregatorRequest',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
