# Generated by Django 5.2.3 on 2025-07-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('config', '0002_balancerequest_balanceresponse_orderqueryrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedorderresponse',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='unifiedorderresponse',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client'),
        ),
    ]
