# Generated by Django 5.2.3 on 2025-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_unifiedorderresponse_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceresponse',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderqueryresponse',
            name='actual_collect_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderqueryresponse',
            name='actual_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderqueryresponse',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderqueryresponse',
            name='payee_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderqueryresponse',
            name='payer_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='actual_collect_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='actual_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='payee_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='payer_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prepaidbillresponse',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prepaidbillresponse',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='actual_collect_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='actual_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='channel_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='payee_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unifiedorderresponse',
            name='payer_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
