# Generated by Django 5.2.3 on 2025-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_balanceresponse_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedorderresponse',
            name='status',
            field=models.CharField(default='pending', max_length=36),
        ),
    ]
