# Generated by Django 5.2.3 on 2025-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_successful_transactions', models.PositiveIntegerField(default=0)),
                ('total_failed_transactions', models.PositiveIntegerField(default=0)),
                ('total_platform_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('total_clients_with_finances', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_clients_with_positive_balance', models.PositiveIntegerField(default=0)),
                ('total_clients_with_negative_balance', models.PositiveIntegerField(default=0)),
                ('total_clients_with_zero_balance', models.PositiveIntegerField(default=0)),
                ('total_clients_with_finances_updated_today', models.PositiveIntegerField(default=0)),
                ('total_clients_with_finances_updated_this_week', models.PositiveIntegerField(default=0)),
                ('total_clients_with_finances_updated_this_month', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Earnings',
                'ordering': ['-last_updated'],
            },
        ),
    ]
