# Generated by Django 5.2.3 on 2025-07-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_platformfeehistory'),
        ('staff', '0006_remove_withdrawhistory_date_withdrawn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_finances',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_finances_updated_this_month',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_finances_updated_this_week',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_finances_updated_today',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_negative_balance',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_positive_balance',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_clients_with_zero_balance',
        ),
        migrations.RemoveField(
            model_name='systemearnings',
            name='total_platform_fees',
        ),
        migrations.CreateModel(
            name='MonthlyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transactions', models.PositiveIntegerField()),
                ('total_successful_transactions', models.PositiveIntegerField()),
                ('total_failed_transactions', models.PositiveIntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_on', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='staff.staff')),
            ],
        ),
    ]
