# Generated by Django 5.2.3 on 2025-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_systemearnings_total_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCommissionAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff Commission Totals',
            },
        ),
    ]
