# Generated by Django 5.2.3 on 2025-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_is_staff_user_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
