# Generated by Django 5.2.3 on 2025-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='user', max_length=10),
        ),
    ]
