# Generated by Django 5.2.3 on 2025-07-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('staff', 'Staff')], default='admin', max_length=10),
        ),
    ]
