# Generated by Django 5.2.3 on 2025-08-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter_index', models.PositiveSmallIntegerField(default=0)),
                ('second_letter_index', models.PositiveSmallIntegerField(default=0)),
                ('number', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Transaction ID Counter',
                'verbose_name_plural': 'Transaction ID Counters',
            },
        ),
    ]
